### ISSUE TITLE
Plugins not loading

### ISSUE THREAD

**Issue by zottelmann** [Kevin-Mattheus-Moerman/Abaqus-Installation-Instructions-for-Ubuntu#3]
Hi Kevin!

Thank you very much for the guide! Everything works beautifully, but abaqus is not loading the standard plugins at startup. There is an error message for each plugin, which is the same:

`File "/opt/SIMULIA/CAE/2018/linux_a64/code/python2.7/lib/abaqus_plugins/rsg/rsg_plugin":
TypeError: unicode() argument 2 must be string, not None`

Did you came across this Problem or do you have an idea how to solve this? I am using Xubuntu 18.04. 
Thank you!

**Comment by zottelmann** [comment]
Hi again. Problem solved. While installing i had to change the System language to "english". That somehow broke the python enviroment. I re-installed the OS this time choosing english as default language. I dont know exactly why, but now it's working.

**Comment by Kevin-Mattheus-Moerman** [comment]
Great, and thanks for posting the apparent solution. Feel free to amend my instructions if you feel they need updating.

**Comment by shivakumargaddam** [comment]
Hi Kevin,

I am facing the same issue in Abaqus 2021. I haven't figured out the fix yet. Could you help?
```
File "/usr/SIMULIA/EstProducts/2023/linux_a64/code/python2.7/lib/abaqus_plugins/amplitudePlotter/amplitudeToolsForm_plugin":
TypeError: unicode() argument 2 must be string, not None
```
