### ISSUE TITLE
chmod -755 error

### ISSUE THREAD

**Issue by lucafranco** [Kevin-Mattheus-Moerman/Abaqus-Installation-Instructions-for-Ubuntu#4]
The installation process blocks on the following screen (and it doesn't move from that page after many hours):

Running chmod -755 over installed files  ...
Running verification.  

Please be patient;  it will take a few minutes to complete.

What can be the solution to this? Thanks in advance

**Comment by franaudo** [comment]
I had the same issue. I have fixed following this guide:
https://github.com/imirzov/Install-Abaqus-2019-on-Ubuntu-18.04-LTS

**Comment by Kevin-Mattheus-Moerman** [comment]
@franaudo thanks for pointing to the solution.
